import {StyleSheet} from 'react-native';

const stylesOutLine = StyleSheet.create({
  outline: {
    width: '23%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#0099FF',
    borderWidth: 1,
  },
  outlineForm0201_tauca: {
    width: 200,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#0099FF',
    borderWidth: 1,
  },
  outlineForm0201_toado: {
    width: 150,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#0099FF',
    borderWidth: 1,
  },
  outlineForm0201_loai: {
    width: 100,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#0099FF',
    borderWidth: 1,
  },
  outlineForm0102: {
    width: 220,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#0099FF',
    borderWidth: 1,
  },
  outlineForm0101_1: {
    width: 150,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#0099FF',
    borderWidth: 1,
  },
  outlineForm0202_1: {
    width: '60%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#0099FF',
    borderWidth: 1,
  },
  outlineForm0301: {
    width: '70%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#0099FF',
    borderWidth: 1,
  },
  outlineForm0301_2: {
    width: '20%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#0099FF',
    borderWidth: 1,
  },
  outlineForm0202_1_2: {
    width: '30%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#0099FF',
    borderWidth: 1,
  },
  textInputOutLine: {
    marginVertical: 10,
    width: '95%',
    fontWeight: '500',
    fontSize: 18,
    padding: 8,
    borderColor: '#0099FF',
    borderWidth: 1,
    color: 'black',
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  textInputOutLineForm0202_1: {
    marginVertical: 10,
    width: '95%',
    fontWeight: '500',
    fontSize: 18,
    padding: 8,
    borderColor: '#0099FF',
    borderWidth: 1,
    color: 'black',
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  textInputOutLineForm0301_1: {
    marginVertical: 10,
    width: '98%',
    fontWeight: '500',
    fontSize: 18,
    padding: 8,
    borderColor: '#0099FF',
    borderWidth: 1,
    color: 'black',
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  textInputOutLineForm0301_2: {
    marginVertical: 10,
    width: '95%',
    fontWeight: '500',
    fontSize: 18,
    padding: 8,
    borderColor: '#0099FF',
    borderWidth: 1,
    color: 'black',
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  textInputOutLineForm0101_1: {
    marginVertical: 5,
    width: '95%',
    fontWeight: '500',
    fontSize: 18,
    padding: 8,
    borderColor: '#0099FF',
    borderWidth: 1,
    color: 'black',
    textAlign: 'center',
    textAlignVertical: 'center',
  },
});

export default stylesOutLine;
