

export const dataMau = {
    "thumua": [
        {
            "tau_bs": "",
            "tm_ct_vt_vido": "",
            "tm_ct_vt_kinhdo": "",
            "loai_1": "",
            "loai_2": "",
            "loai_3": "",
            "loai_4": "",
            "loai_5": "",
            "loai_6": "",
            "loai_1_kl": "",
            "loai_2_kl": "",
            "loai_3_kl": "",
            "loai_4_kl": "",
            "loai_5_kl": "",
            "loai_6_kl": "",
            "tongsanluong": "",
        },
        {

            "tau_bs": "",
            "tm_ct_vt_vido": "",
            "tm_ct_vt_kinhdo": "",
            "loai_1": "",
            "loai_2": "",
            "loai_3": "",
            "loai_4": "",
            "loai_5": "",
            "loai_6": "",
            "loai_1_kl": "",
            "loai_2_kl": "",
            "loai_3_kl": "",
            "loai_4_kl": "",
            "loai_5_kl": "",
            "loai_6_kl": "",
            "tongsanluong": "",
        },
        {

            "tau_bs": "",
            "tm_ct_vt_vido": "",
            "tm_ct_vt_kinhdo": "",
            "loai_1": "",
            "loai_2": "",
            "loai_3": "",
            "loai_4": "",
            "loai_5": "",
            "loai_6": "",
            "loai_1_kl": "",
            "loai_2_kl": "",
            "loai_3_kl": "",
            "loai_4_kl": "",
            "loai_5_kl": "",
            "loai_6_kl": "",
            "tongsanluong": "",
        },
        {

            "tau_bs": "",
            "tm_ct_vt_vido": "",
            "tm_ct_vt_kinhdo": "",
            "loai_1": "",
            "loai_2": "",
            "loai_3": "",
            "loai_4": "",
            "loai_5": "",
            "loai_6": "f",
            "loai_1_kl": "",
            "loai_2_kl": "",
            "loai_3_kl": "",
            "loai_4_kl": "",
            "loai_5_kl": "",
            "loai_6_kl": "",
            "tongsanluong": "",
        },
        {

            "tau_bs": "",
            "tm_ct_vt_vido": "",
            "tm_ct_vt_kinhdo": "",
            "loai_1": "",
            "loai_2": "",
            "loai_3": "",
            "loai_4": "",
            "loai_5": "",
            "loai_6": "",
            "loai_1_kl": "",
            "loai_2_kl": "",
            "loai_3_kl": "",
            "loai_4_kl": "",
            "loai_5_kl": "",
            "loai_6_kl": "",
            "tongsanluong": "",
        },
    ],
    "thongtintaudc_thumua": [
        {
            "tau_bs": "",
            "tau_chieudailonnhat": "",
            "tau_tongcongsuatmaychinh": "",
            "gpkt_so": "",
            "nghekt": "",
            "cang_di": "",
            "thongtinhoatdong": [
                {

                    "methu": "",
                    "vido_tha": "",
                    "kinhdo_tha": "",
                    "vido_thu": "",
                    "kinhdo_thu": "",
                    "loai_1": "",
                    "loai_2": "",
                    "loai_3": "",
                    "loai_4": "",
                    "loai_5": "",
                    "loai_6": "",
                    "loai_1_kl": "",
                    "loai_2_kl": "",
                    "loai_3_kl": "",
                    "loai_4_kl": "",
                    "loai_5_kl": "",
                    "loai_6_kl": "",
                    "tongsanluong": "",
                },
                {

                    "methu": "",
                    "vido_tha": "",
                    "kinhdo_tha": "",
                    "vido_thu": "",
                    "kinhdo_thu": "",
                    "loai_1": "",
                    "loai_2": "",
                    "loai_3": "",
                    "loai_4": "",
                    "loai_5": "",
                    "loai_6": "",
                    "loai_1_kl": "",
                    "loai_2_kl": "",
                    "loai_3_kl": "",
                    "loai_4_kl": "",
                    "loai_5_kl": "",
                    "loai_6_kl": "",
                    "tongsanluong": "",
                },
                {

                    "methu": "",
                    "vido_tha": "",
                    "kinhdo_tha": "",
                    "vido_thu": "",
                    "kinhdo_thu": "",
                    "loai_1": "",
                    "loai_2": "",
                    "loai_3": "",
                    "loai_4": "",
                    "loai_5": "",
                    "loai_6": "",
                    "loai_1_kl": "",
                    "loai_2_kl": "",
                    "loai_3_kl": "",
                    "loai_4_kl": "",
                    "loai_5_kl": "",
                    "loai_6_kl": "",
                    "tongsanluong": "",
                },
                {

                    "methu": "",
                    "vido_tha": "",
                    "kinhdo_tha": "",
                    "vido_thu": "",
                    "kinhdo_thu": "",
                    "loai_1": "",
                    "loai_2": "",
                    "loai_3": "",
                    "loai_4": "",
                    "loai_5": "",
                    "loai_6": "",
                    "loai_1_kl": "",
                    "loai_2_kl": "",
                    "loai_3_kl": "",
                    "loai_4_kl": "",
                    "loai_5_kl": "",
                    "loai_6_kl": "",
                    "tongsanluong": "",
                },
                {

                    "methu": "",
                    "vido_tha": "",
                    "kinhdo_tha": "",
                    "vido_thu": "",
                    "kinhdo_thu": "",
                    "loai_1": "",
                    "loai_2": "",
                    "loai_3": "",
                    "loai_4": "",
                    "loai_5": "",
                    "loai_6": "",
                    "loai_1_kl": "",
                    "loai_2_kl": "",
                    "loai_3_kl": "",
                    "loai_4_kl": "",
                    "loai_5_kl": "",
                    "loai_6_kl": "",
                    "tongsanluong": "",
                }
            ]
        }
    ],
    "dairy_name": "filemau",

}